version: '3'
services:
  gateway:
    container_name: core.mor.local
    build: ./nginx
    volumes:
      - ./nginx/nginx-default.development.conf:/etc/nginx/conf.d/default.conf
      - ./media:/media
    depends_on:
      core_app:
        condition: service_started
    ports:
      - 8002:8002
    networks:
      - mor_bridge_network
    env_file:
      - .env.local
  core_app:
    build: ./app
    env_file:
      - .env.local
    volumes:
      - ./app:/app
      - ./media:/media
    depends_on:
      database:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - mor_network
      - mor_bridge_network
    command: ["bash", "/app/deploy/docker-entrypoint.development.sh"]
    restart: always

  database:
    image: postgis/postgis:16-3.4
    shm_size: '1024m'
    ports:
      - "7998:5432"
    env_file:
      - .env.local
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres-data-16:/var/lib/postgresql/data
      - ./bin/init-database.sh:/docker-entrypoint-initdb.d/init-database.sh
    networks:
      - mor_network

  redis:
    image: redis
    networks:
      - mor_network
    ports:
      - "6379"

  core_celery_worker:
    build: ./app
    command: "celery -A config worker -l info"
    depends_on:
      database:
        condition: service_started
      redis:
        condition: service_started
    volumes:
      - ./media:/media
    env_file:
      - .env.local
    networks:
      - mor_network
      - mor_bridge_network
    # restart: on-failure

  core_app_celery_beat:
    build: ./app
    command: "celery -A config beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler"
    depends_on:
      database:
        condition: service_started
      redis:
        condition: service_started
    volumes:
      - ./media:/media
    env_file:
      - .env.local
    networks:
      - mor_network
      - mor_bridge_network
    # restart: on-failure

  flower:
    image: mher/flower
    container_name: flower
    command: celery flower
    working_dir: /data
    networks:
      - mor_network
    ports:
      - 5555:5555
    env_file:
      - .env.local
    environment:
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: db+postgresql+psycopg2://${DATABASE_USER}:${DATABASE_PASSWORD}@${DATABASE_HOST_OVERRIDE}:${DATABASE_PORT_OVERRIDE}/django-db
    depends_on:
      - core_celery_worker
      - database
      - redis

volumes:
  postgres-data-16:

networks:
  mor_network:
    external: true
  mor_bridge_network:
    external: true
